--- # test for blockline
- hosts: web
  tasks:
    - name: Add mappings to /home/user/blockline
      blockinfile:
          path: /home/user/blockline
          create: yes
          block: |
            {{ item.ip }} {{ item.name }}
          marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      with_items:
        - { name: host1, ip: 10.10.1.10 }
        - { name: host2, ip: 10.10.1.11 }
        - { name: host3, ip: 10.10.1.12 }
    - name: remove HTML as well as surrounding markers
      blockinfile:
          path: /home/user/blockline2
          create: yes
          marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
          content: ""
