--- # ansible playbook
- hosts: web
  sudo: yes
  connection: ssh
  remote_user: user
  vars:
   ansible_sudo_pass: "shiyang123"
#   python -c 'python -c 'import crypt; print crypt.crypt("shi", "ansible")'
  gather_facts: no
  tasks:
   - name: create a group
     group: name=test state=present
   - name: create a user
     user: name=ansible password=an/ILRUZ7p4OE comment="ansible" shell=/bin/bash group=test state=present createhome=yes generate_ssh_key=yes
   - name: access to ansible with user
     authorized_key: user=ansible key="{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}" state=absent
   - name: check the user
     become: yes
     shell: compgen -u
     register: user_list
   - name: debug process
#     debug: var="user_list"
     debug: msg=" tst user is created"
     when: "'tst' in user_list.stdout_lines"
#   - name: remove the user
#     user: name=tst state=absent remove=yes


 
  
  
